### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kostaonguard** [shramee/social-star-rating#1]
Where do I place `<?php do_action('plugin_name_hook'); ?>` in my template? Is it into functions.php? , e.g. <?php do_action('social-star-rating_hook'); ?>

**Comment by shramee** [comment]
Hi @kostaonguard,
Sorry, not sure what you are trying to do... Could you explain more..?

**Comment by kostaonguard** [comment]
I am trying to install your plugin.

https://github.com/shramee/social-star-rating/blob/master/README.txt says: 
== Installation ==
This section describes how to install the plugin and get it working.
e.g.

1. Upload `social-star-rating.php` to the `/wp-content/plugins/` directory
1. Activate the plugin through the 'Plugins' menu in WordPress
1. Place `<?php do_action('plugin_name_hook'); ?>` in your templates
======
So I was wondering where to put this line `<?php do_action('plugin_name_hook'); ?>`  in my template files. Sorry for stupid question. :)

**Comment by kostaonguard** [comment]
Should I add the line in my theme's function.php like this?: `<?php do_action('social_star_rating'); ?>`

**Comment by shramee** [comment]
Sorry, that's just starter I used...
It's not ready for public use yet... Still if you want to use it...
you can use shortcode `[social-start-rating]` on any post/page content.

It will need social integrations in code (Google Places, Facebook, Yelp and Healthy Hearing) for anyone to be able to use it as there is no admin page at the moment...

If you are fluent in PHP you can do it your self, else you'll need to hire a developer to do that for you.
